name: Build Docker Images for Multiple Branches

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "1.21.0", "1.21.4" ]
    env:
      DOCKERHUB_IMAGE: kumpelinus/zenith-proxy
    steps:
      - name: Checkout Dependent Repo
        uses: actions/checkout@v3

      - name: Get Upstream Commit Hash for branch ${{ matrix.branch }}
        id: upstream
        run: |
          git clone https://github.com/rfresh2/ZenithProxy.git upstream-repo
          cd upstream-repo
          git checkout ${{ matrix.branch }}
          COMMIT=$(git rev-parse HEAD)
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV
          echo "::set-output name=commit::$COMMIT"
          echo "Upstream commit hash for branch ${{ matrix.branch }}: $COMMIT"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and Push Docker Image for branch ${{ matrix.branch }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.branch }}
          build-args: |
            BRANCH=${{ matrix.branch }}

      # Conditional step: if branch is "1.21.4", add the "latest" tag.
      - name: Tag image as latest for branch 1.21.4
        if: matrix.branch == '1.21.4'
        run: |
          docker pull ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.branch }}
          docker tag ${{ env.DOCKERHUB_IMAGE }}:${{ matrix.branch }} ${{ env.DOCKERHUB_IMAGE }}:latest
          docker push ${{ env.DOCKERHUB_IMAGE }}:latest

